Repository halo-sigs/charts, pull requests merged in 2022-12, with the labels that each got.

#1 docs: refine README and add readme-generator
  .gitignore
  README.md
  charts/halo/values.yaml
  package.json
  pnpm-lock.yaml
Labels: release-note

#3 Update OWNERS
  OWNERS
Labels: release-note-none

#2 Bump chart version to 1.0.1
  charts/halo/Chart.yaml
Labels: lgtm, approved, release-note-none

#4 Correct Helm Charts repository URL
  README.md
Labels: lgtm, approved, release-note-none
